@startuml
'https://plantuml.com/class-diagram
skinparam ranksep 250
left to right direction

package pages {

    BasePage <|-- MainPage
    BasePage <|-- LoginPage

    abstract class BasePage {
    _ _init_ _(self, browser, url, timeout=10)
    open(self)
    is_element_present(self, how, what)
    }

    class MainPage <main_page.py>{
    go_to_login_page(self)
    should_be_login_link(self)
    }

    class LoginPage <<login_page.py>>{
    should_be_login_page(self)
    should_be_login_url(self)
    should_be_login_form(self)
    should_be_register_form(self)
    }

    package locators {
        class MainPageLocators {
        LOGIN_LINK
        }

        class LoginPageLocators {
        LOGIN_URL
        LOGIN_FORM
        REGISTER_FORM
        }
    }
}

package main {

    class conftest {
    pytest_addoption(parser)
    browser(request)
    }

    class test_main_page {
    test_guest_can_go_to_login_page(browser)
    test_guest_should_see_login_link(browser)
    }
}

hide conftest circle
hide test_main_page circle

test_main_page::test_guest_can_go_to_login_page -[dashed]- MainPage::go_to_login_page
test_main_page::test_guest_can_go_to_login_page -[dashed]- LoginPage::should_be_login_page

test_main_page::test_guest_should_see_login_link -[dashed]- MainPage::should_be_login_link

'MainPage::should_be_login_link -[dashed]- BasePage::is_element_present
'LoginPage::should_be_login_form -[dashed]- BasePage::is_element_present
'LoginPage::should_be_register_form -[dashed]- BasePage::is_element_present

test_main_page -[dashed]- conftest
@enduml